[project]
name = "callback"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "agentops>=0.4.13",
    "gohumanloop>=0.0.9",
    "langgraph>=0.4.7",
]
