[project]
name = "agentops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gohumanloop>=0.0.8",
    "langgraph>=0.4.7",
]
